veldrid/veldrid

src/Veldrid/CommandList.cs
Discovered when my application was getting an Access Violation in a
memmove function when trying to copy a 512x128 texture from staging to
an ordinary sampled texture.
Didn't crash on Windows at all, but crashed consistently on Mac OS X.
.NET Core (& VS Mac aka MonoDevelop) was uniquely unhelpful in debugging. 
(Kept crashing in breakpoints before the actual copy, even on the right thread. I eventually found this line of code was the culprit after much Console.WriteLine()ing and delaying threads with sleep commands. Sigh...)
Veldrid is cool though. I'm enjoying using it so far. 👍
=> Fix copying non-square OpenGL textures

src/Veldrid.SDL2/Sdl2.Window.cs, src/Veldrid.SDL2/Sdl2Window.cs
This PR adds an second `Sdl2Window` constructor that allows creation from an existing window handle.
This is useful for embedding into editor UIs - although AFAIK, Windows is the only platform where `SDL_CreateWindowFrom` accepts the handle of a non-window-level control, which limits its usefulness.
This is a speculative PR - I don't know whether this matches your vision for the `Sdl2Window` API. It would be really useful for me because I'd like to use the `Sdl2Window` abstraction, both for the game and also embedded in a (Windows-only-at-the-moment) editor.
My implementation could undoubtedly be improved, although because this is internal and there probably won't be a 3rd way to construct windows, I didn't want to over-engineer it.
=> Add Sdl2Window constructor that allows creation from an existing window handle

src/Veldrid/BlendAttachmentDescription.cs, src/Veldrid/BlendStateDescription.cs, src/Veldrid/DepthStencilStateDescription.cs, src/Veldrid/RasterizerStateDescription.cs
This PR adds these state descriptions:
* `BlendAttachmentDescription.Disabled`
* `BlendStateDescription.SingleAdditiveBlend`
* `BlendStateDescription.SingleDisabled`
* `DepthStencilStateDescription.DepthOnlyLessEqualRead`
* `RasterizerStateDescription.CullNone`
These are only quality-of-life improvements, nothing critical. XNA has all these and I personally find them useful.
Let me know if you'd like some but not others, and I can update the PR.
=> Implement some additional helper state descriptions

src/Veldrid.Tests/TextureTests.cs, src/Veldrid/D3D11/D3D11Formats.cs, src/Veldrid/FormatHelpers.cs, src/Veldrid/MTL/MTLFormats.cs, src/Veldrid/OpenGL/OpenGLFormats.cs, src/Veldrid/OpenGL/OpenGLTextureView.cs, src/Veldrid/PixelFormat.cs, src/Veldrid/Vk/VkFormats.cs
This PR implements `R8_G8_SNorm` and `R32_G32_B32_A32_UInt` pixel formats and hooks these new values up to the D3D11, Metal, Vulkan, and OpenGL backends.
I have added new tests, although I thought that with the growing number of pixel formats, it might be handy to have a single test that we can extend with new pixel formats, rather than copying-and-pasting?
I'll follow up with the BC1 and BC2 compressed formats in a separate PR.
=> Implement R8_G8_SNorm and R32_G32_B32_A32_UInt pixel formats

src/Veldrid.StartupUtilities/Veldrid.StartupUtilities.csproj, src/Veldrid.StartupUtilities/VeldridStartup.cs, src/Veldrid/GraphicsDevice.cs, src/Veldrid/Util.cs, src/Veldrid/Veldrid.csproj
Added defines FEATURE_D3D11_BACKEND, FEATURE_METAL_BACKEND, FEATURE_OPENGL_BACKEND, besides FEATURE_VULKAN_BACKEND. Allows you to individually disable backends that you don't need.
=> Added defines to exclude unneeded backends

src/Veldrid.StartupUtilities/VeldridStartup.cs
Those formats were supported by all other backends, but still missing for the OpenGL backend.
=> Add missing depth buffer formats to the OpenGL backend

src/Veldrid/GraphicsDeviceOptions.cs, src/Veldrid/GraphicsPipelineDescription.cs, src/Veldrid/MTL/MTLCommandList.cs, src/Veldrid/MTL/MTLGraphicsDevice.cs, src/Veldrid/MTL/MTLPipeline.cs, src/Veldrid/ResourceBindingModel.cs
Matches the behaviour change in https://github.com/mellinoe/ShaderGen/pull/36.
`BindMetalVertexBuffersAfterOtherBuffers` is obviously just a placeholder name - do you have suggestions for a better name?
=> Add configurable option to bind vertex data buffers after other vertex-stage uniform and structured buffers in Metal backend

src/Veldrid/MTL/MTLPipeline.cs
=> Use correct index for accessing vertex buffer layouts

src/Veldrid.StartupUtilities/VeldridStartup.cs
In our game, the user can optionally override the renderer backend. But because there's no overload of `CreateWindowAndGraphicsDevice` that accepts a `GraphicsBackend?`, we need to conditionally call the overload that does / doesn't accept a `GraphicsBackend`.
With this change, we can do this:
``` csharp
GraphicsBackend? preferredBackend = null;
if (something)
{
preferredBackend = GraphicsBackend.Direct3D11; // read from CLI argument
}
VeldridStartup.CreateWindowAndGraphicsDevice(
windowCreateInfo,
graphicsDeviceOptions,
preferredBackend ?? VeldridStartup.GetPlatformDefaultBackend(),
out _window,
out _device);
```
=> Make VeldridStartup.GetPlatformDefaultBackend public

src/Veldrid/OpenGL/NoAllocEntryList/NoAllocUpdateBufferEntry.cs, src/Veldrid/OpenGL/NoAllocEntryList/OpenGLNoAllocCommandEntryList.cs, src/Veldrid/OpenGL/OpenGLCommandExecutor.cs, src/Veldrid/OpenGL/OpenGLCommandList.cs, src/Veldrid/OpenGL/OpenGLGraphicsDevice.cs, src/Veldrid/OpenGL/OpenGLResourceFactory.cs, src/Veldrid/OpenGL/OpenGLShader.cs, src/Veldrid/StagingMemoryPool.cs
This change noticeably improves performance (mainly) in scenarios that involve lots of texture updates, such as video playback.
A few things to note:
- The pool returns *the smallest* block that is big enough to store the requested amount of data.
- ``GraphicsDevice`` now owns (the only instance of) the pool.
- ``StagingMemoryPool`` now has a ``Dispose`` method which frees all the native memory. The execution thread is responsible for calling it.
- Each ``CommandList`` has its own list of staging blocks, which is flushed when the ``CommandList`` is disposed. This presents a problem if a ``CommandList`` is disposed after the ``GraphicsDevice``, which owns the memory pool. This is currently addressed by adding [this check](https://github.com/SomeAnon42/veldrid/blob/c6f73d4e11dfbbf825adff2e8b …
=> Rewrite StagingMemoryPool to use unmanaged memory blocks

src/Veldrid.SDL2/Sdl2Window.cs
_cachedPosition only gets updated via SDL_WindowEventID.Moved
if try to change both X and Y then second call to SetWindowPosition will use old cached value
Example
```c#
Sdl2Window _window;
_window.X = newX; // SetWindowPosition(newX, _cachedPosition.Value.Y)
_window.Y = newY; // SetWindowPosition(_cachedPosition.Value.X, newY) // BAD
```
Maybe and/or make Sdl2Window.SetWindowPosition public ?
=> Update cached position on move

src/Veldrid.StartupUtilities/VeldridStartup.cs
Suggested change, please modify any way you see fit. Thank you
MESA drivers on Linux distros do not appear to return contexts higher than OpenGL 3.0 unless a Forward Compatible (no depreciated features) Core context is requested. The latest MESA drivers appear to sometimes not require this fix, but this improved behaviour appears unrealiabe under my limited testing.
=> OpenGL Context is now requested with ForwardCompatible Flag

src/Veldrid/Vk/VkSwapchainFramebuffer.cs
Saw this when profiling allocations
=> [Vulkan] Avoid hidden enumerator allocations

src/Veldrid/BlendAttachmentDescription.cs, src/Veldrid/BufferDescription.cs, src/Veldrid/DepthStencilStateDescription.cs, src/Veldrid/FramebufferDescription.cs, src/Veldrid/GraphicsPipelineDescription.cs, src/Veldrid/OutputAttachmentDescription.cs, src/Veldrid/OutputsDescription.cs, src/Veldrid/RasterizerStateDescription.cs, src/Veldrid/ResourceLayoutElementDescription.cs, src/Veldrid/SamplerDescription.cs, src/Veldrid/ShaderDescription.cs, src/Veldrid/SpecializationConstant.cs, src/Veldrid/StencilBehaviorDescription.cs, src/Veldrid/TextureDescription.cs, src/Veldrid/Util.cs, src/Veldrid/VertexElementDescription.cs
* Replace GetHashCode/Equals calls on enums with casts to int.
* Manually compare nullable values as Nullable does not implement ``IEquatable<T?>``. See ``Util.NullableEquals`` and ``GraphicsPipelineDescription.Equals``.
The BCL has ``Nullable.Equals<T>``, but it performs considerably worse than a custom implementation.
=> Avoid allocations when calling GetHashCode or Equals on certain structs

src/Veldrid/D3D11/D3D11ResourceCache.cs
Currently, input layouts with a non-zero InstanceStepRate aren't properly cached. Requesting the same input layout twice results in an exception. https://github.com/mellinoe/veldrid/blob/d7b6425fe1b502bfefe7eebd4002801a13881eb1/src/Veldrid/D3D11/D3D11ResourceCache.cs#L167
There is a mismatch between the "temporary" key and the "permanent" key in the dictionary, since only the temporary key has the correct InstanceStepRate value. This results in an attempt to add the same InputLayout to the cache under the same (incorrectly generated) key,
Repro:
```csharp
(Shader vs, Shader fs) = LoadShaderSet(factory, "ShaderSetName");
var shaderSetDesc = new ShaderSetDescription(
new[] { vertexLayout, perInstanceDataLayout }, // has a VertexLayout with a non-0 InstanceStepRate
new[] { vs, fs });
// ... …
```
=> [D3D11] Respect InstanceStepRate when creating InputLayoutCacheKey

src/Veldrid.Tests/TextureTests.cs, src/Veldrid/GraphicsDevice.cs
I found this bug because one SAGE texture is BC1-compressed, but sized 2 x 512. The mipmap data still needs to be multiple-of-four-sized, but this isn't currently allowed by Veldrid.
=> Allow non-multiple-of-four-sized texture to be updated with multiple-of-four mipmap data

src/Veldrid/D3D11/D3D11TextureView.cs
I assume this was a typo - at the moment, it's impossible to create a `TextureView` for anything other than the first array layer in a `Texture2D`  (assuming it has `ArrayLayers > 1`, and assuming you want all mip levels in the texture view).
=> Fix D3D11 TextureView creation for arrayLayer > 0

Directory.Build.props
Fixes #119 without needing to install `libcurl3` on Ubuntu 18.04 (and presumably newer).
=> Fix build failure on Ubuntu 18.04

src/Veldrid/D3D11/D3D11Swapchain.cs
Change to "Height" instead of "Width"
=> Fix typo in D3D11Swapchain

src/Veldrid/D3D11/D3D11TextureView.cs, src/Veldrid/D3D11/D3D11Util.cs, src/Veldrid/Vk/VkTextureView.cs
The current code does not account for the existence of 1D textures.
- The Metal backend seems to handle this case correctly, though I can't verify that
- ~~OpenGL doesn't actually have TextureViews, so no changes are required~~
Wrong. There is in fact a code path that uses glTextureView, but it isn't taken when creating a full TextureView, which is why I'm not experiencing any issues. Changes might be required.
- D3D11 and Vulkan are covered by this PR
Maybe we should add some tests, though I'm not sure if it's possible to verify anything other than the fact that creating a TextureView succeeds for 1D textures.
=> [D3D11, Vulkan] Handle 1D textures correctly when creating a TextureView

src/Veldrid.SDL2/Sdl2.Joystick.cs
Makes it possible to get joystick instance id from SDL_Joystick
=> Add wrapper for SDL_JoystickInstanceID

src/Veldrid/OpenGL/OpenGLCommandExecutor.cs
This fixes the misalignment of scissor rects when the viewport is not a full view of the framebuffer.
=> [OpenGL] Set scissor rect relative to framebuffer, not viewport.

src/Veldrid/OpenGL/OpenGLFormats.cs
The previous mapping to Clamp caused a glError of INVALID_ENUM on OSX, but ClampToEdge is supported.
=> Fix SamplerAddressMode.Clamp mapping in OpenGL

src/Veldrid/MTL/MTLFormats.cs
Mapping Mirror to MirrorRepeat instead of MirrorClampToEdge to be consistent with the other backends (at the very least OpenGL backend which I tested it looks identical, but looking at the code I think the other backends as well).
=> Fix mirror sampler address mode on metal

src/Veldrid.ImGui/ImGuiRenderer.cs
This allows for overriding the `Update` method and handle the input in a different way.
```cs
public new void Update(float deltaSeconds, object mycustominput)
{
BeginUpdate(deltaSeconds);
// handle custom input
EndUpdate();
}
```
=> Change ImGui update method to use protected methods

src/Veldrid.SDL2/Rectangle.cs
Was doing some stuff with the Rectangle class defined in Veldrid.SDL2 and noticed it seems to have an off-by-one error. Compared against the behaviour of System.Drawing.Rectangle to verify.
=> Fix off-by-one issue in Veldrid.Rectangle

src/Veldrid.SDL2/Rectangle.cs
Noticed that I was writing a lot of code like "new Vector2(rect.Width, rect.Height)" and "new Vector2(rect.X, rect.Y)" when working with rectangles, so thought it would be a good idea to add some properties to simplify things.
=> Add "position" and "size" Vector2 convenience properties to Veldrid.Rectangle.

src/Veldrid.SDL2/Sdl2Window.cs
Subscribing to `CloseRequested` and returning `true` will abort the close action.  This allows users to provide "are you sure?" dialogs, etc.
This will catch both programmatic `Close()` calls and explicit user actions (clicking the window close button, Alt+F4, Cmd+Q).
Tested on macOS by manually inserting into NeoDemo: `_window.CloseRequested += () => true;`
=> Add event to optionally abort closing the SDL2 window

src/Veldrid.SDL2/Sdl2.Window.cs
I needed to use these two functions from SDL and couldn't see them in the Sdl2Native class so just thought I would add them in.
SDL_GetDesktopDisplayMode is useful to get the desktop resolution in a cross-platform way.
=> Added delegates for SDL_GetDesktopDisplayMode and SDL_GetNumVideoDisplays

src/Veldrid/GraphicsPipelineDescription.cs
Change "resoruces" to "resources"
=> Fix typo in GraphicsPipelineDescription

src/Veldrid/OpenGL/OpenGLCommandExecutor.cs
This fixes `OpenGLCommandExecutor.ClearColorTarget` not resetting the draw buffers after clearing the target.
(Fixes #251)
=> [OpenGL] Reset the draw buffers after clearing a color target.

src/Veldrid/Vk/VkCommandList.cs, src/Veldrid/Vk/VkFramebuffer.cs
These instances of `foreach` were causing a lot of allocations, making the GC trigger extremely often.
=> [Vulkan] Replace some foreachs that were causing lots of allocations.

src/Veldrid.SDL2/KeyEvent.cs, src/Veldrid.SDL2/Sdl2Window.cs
Small change to add key repeat info to KeyEvent
Also - quick question - what's the policy on breakages for Veldrid? If I didn't have the default parameter for `repeat` on the `KeyEvent` constructor, would that be a breaking change? If so, would you have to release a new major version? i.e. `5.0.0`, or would it be a minor version increment? i.e. `4.8.0`
Also - is the change of the `ToString` function breaking behaviour, in your opinion?
=> Add key repeat info to KeyEvent

src/Veldrid.SDL2/Sdl2.GameController.cs
Seems like an oversight - I'm going to use this event to handle the ControllerDeviceAdded/Removed/Remapped events https://wiki.libsdl.org/SDL_ControllerDeviceEvent
=> Make SDL_ControllerDeviceEvent public

src/Veldrid.MetalBindings/Veldrid.MetalBindings.csproj, src/Veldrid.SDL2/Veldrid.SDL2.csproj, src/Veldrid/D3D11/D3D11Buffer.cs, src/Veldrid/D3D11/D3D11CommandList.cs, src/Veldrid/D3D11/D3D11Formats.cs, src/Veldrid/D3D11/D3D11Framebuffer.cs, src/Veldrid/D3D11/D3D11GraphicsDevice.cs, src/Veldrid/D3D11/D3D11Pipeline.cs, src/Veldrid/D3D11/D3D11ResourceCache.cs, src/Veldrid/D3D11/D3D11ResourceFactory.cs, src/Veldrid/D3D11/D3D11Sampler.cs, src/Veldrid/D3D11/D3D11Shader.cs, src/Veldrid/D3D11/D3D11Swapchain.cs, src/Veldrid/D3D11/D3D11Texture.cs, src/Veldrid/D3D11/D3D11TextureView.cs, src/Veldrid/D3D11/D3D11Util.cs, src/Veldrid/D3D11DeviceOptions.cs, src/Veldrid/GraphicsDevice.cs, src/Veldrid/SwapchainSource.cs, src/Veldrid/Veldrid.csproj
Since SharpDX has been archive and is not developed anymore (see https://github.com/sharpdx/SharpDX), it has to be replaced if new features like mesh shaders or raytracing shaders. I'm planning to do a D3D12 based on this afterwards.
@amerkoleci created a library called [Vortice.Windows](https://github.com/amerkoleci/Vortice.Windows/), which has similar goals and is actively developed. 
It is much closer to the original C++ Api, due to it's SharpGen usage.
I'm opening this as a draft since there are still some things that need to be figured out before.
=> Replace SharpDX with Vortice.Windows

src/Veldrid/D3D11/D3D11CommandList.cs, src/Veldrid/D3D11/D3D11GraphicsDevice.cs, src/Veldrid/D3D11/D3D11Swapchain.cs, src/Veldrid/D3D11/D3D11Util.cs, src/Veldrid/Veldrid.csproj
This fixes:
- ID3D11CommandList leakage with new method.
- ReportLiveObjects during D3D11 device dispose which was wrong.
- Staging buffers not being disposed.
- Calls non array ID3D11DeviceContext methods.
=> D3D11 fix and leakage improvements

src/Veldrid/D3D11/D3D11CommandList.cs
With the Vortice update looks like the src & dest parameters to the `ResolveSubresource` have been swapped around to more closely match the C api - now dest is first -- see https://github.com/amerkoleci/Vortice.Windows/blob/master/src/native/include/d3d12.h#L5530-L5535 vs https://github.com/sharpdx/SharpDX/blob/1f89381bc08f2d8cf8d294c6c5fce8dc85a849a1/Source/SharpDX.Direct3D11/DeviceContext.cs#L222-L224
This update switches the parameters around to fix this regression.
To check, try running NeoDemo & turning on MSAA in this commit vs master.
=> Fix ResolveTextureCore

src/Veldrid.OpenGLBindings/Enums.cs, src/Veldrid/OpenGL/OpenGLUtil.cs
Ran into a small error where I set too long names for OpenGL - this limits the length of those names
=> Cap length of OpenGL debug names

src/Veldrid/OpenGL/OpenGLCommandExecutor.cs
Fixes #312.
I don't have access to a development Windows machine at this moment (no bandwidth to set it up now) so I can't run the tests, but the NeoDemo seems to be working fine (Linux, OpenGL backend).
P.S.: Is there any plans for adding .gitattributes file to the repository? I've tried to commit the patch from a Linux machine, but it produced a full rewrite because the source file was misinterpreted as binary one because of the BOM mark at the start of the file.
Had to use the Github web interface to make this patch :neutral_face:
=> Fixed redundant OpenGL vertex layout calls (#312)

src/Veldrid/D3D11/D3D11GraphicsDevice.cs, src/Veldrid/GraphicsDevice.cs, src/Veldrid/MTL/MTLGraphicsDevice.cs, src/Veldrid/OpenGL/OpenGLGraphicsDevice.cs, src/Veldrid/Vk/VkGraphicsDevice.cs
This allows users of the library to access the debug name of the graphics device, so that it can be displayed to the user for debugging.
Tested every backend except for Metal, as I don't have a Mac. I see no reason why it shouldn't work though.
=> Add Name property to GraphicsDevice

src/Veldrid.SDL2/Sdl2.Window.cs
Similar to #308, adds two extra functions that I plan to use to get the current display size.
`SDL_GetWindowDisplayIndex` is to get the display that that a window is currently on.
`SDL_GetCurrentDisplayMode` is to get the size of that display.
I don't want to use `SDL_GetDesktopDisplayMode` as according to the documentation the result of this method doesn't change when a window is fullscreen on the display with a different resolution, whereas I would want the changed resolution.
Also: unintentional, but it changes the line endings of the file to be uniformly LF. Can change back if wanted
=> Add SDL_GetWindowDisplayIndex and SDL_GetCurrentDisplayMode

src/Veldrid/D3D11/D3D11GraphicsDevice.cs, src/Veldrid/GraphicsDevice.cs, src/Veldrid/MTL/MTLGraphicsDevice.cs, src/Veldrid/OpenGL/OpenGLGraphicsDevice.cs
Fix for https://github.com/mellinoe/veldrid/issues/324.  
Could be nice to have a ConvertNanosecondsToWaitHandleMs() somewhere accessible to all of them, but I wasn't sure where that would go.
=> Fixed infinite WaitForFences throwing.

src/Veldrid/OpenGL/OpenGLGraphicsDevice.cs
Use the created framebuffer object instead of a texture object when binding an OpenGL framebuffer.
=> Resolved Isssue with using wrong variable for glBindFrameBuffer

src/Veldrid/OpenGL/OpenGLCommandExecutor.cs
Allow for none square compressed texture update to be supported. The OpenSage is crashing when updating non-square compressed textures.
=> Allow non square compressed texture update support.

src/NeoDemo/Camera.cs, src/NeoDemo/NeoDemo.cs
Somehow this doesn't throw on Windows.
On Linux you get a segfault if you try to use the stale Sdl2Window.
=> Fixed window becoming stale in NeoDemo Camera

src/Veldrid/OpenGL/NoAllocEntryList/OpenGLNoAllocCommandEntryList.cs
Making sure that the indirect draw indexed command is recorded for OpenGL.
=> Add indirect draw indexed entry for OpenGL

src/Veldrid/Vk/VkCommandList.cs
I found an error in VkCommandList caused by using two Compute Pipelines in the same CommandList. When dispatching the pipeline with fewer resources the loop inside VkCommandList.PreDispatchCommand would throw an exception because it would loop past the number of resource sets that had actually been bound. I have changed VkCommandList to use the number of resources in the current pipeline instead of the length of the array.
=> Use Pipeline ResourceSetCount Instead of Array Length

src/Veldrid/D3D11/D3D11ResourceCache.cs
This PR fixes the "IndependentBlendEnable" boolean in the D3D11 blend state not being set to true.
=> [D3D11] Fix independent blends not being enabled.

src/Veldrid/OpenGL/OpenGLExtensions.cs, src/Veldrid/OpenGL/OpenGLGraphicsDevice.cs
Added feature check on buffer range binding and anisotropic filtering since they are not guaranteed to be supported on all OpenGL devices.
=> Check Feature Support on OpenGL

src/Veldrid/Vk/VkCommandList.cs, src/Veldrid/Vk/VkResourceSet.cs
This focuses mostly on removing virtual dispatch from passing around internal Lists as IReadOnlyList.
=> [Vulkan] CommandList micro-optimizations

src/Veldrid/Vk/VkDescriptorPoolManager.cs, src/Veldrid/Vk/VulkanUtil.cs
vkDescriptorPool guards free's and resource tracking with a lock but doesn't guard the actual allocation of memory.
To illustrate this, run something like this from the NeoDemo sample (with preferred backend set to Vk). It should crash with undefined behaviour within a minute (usually a false 'pool out of memory' error). After this lock is added it will no longer crash.
`
void CrashMe()
{
void ThreadProc()
{
ResourceLayout rl = _gd.ResourceFactory.CreateResourceLayout(
new ResourceLayoutDescription(
new ResourceLayoutElementDescription("sampler" + System.Threading.Thread.CurrentThread.ManagedThreadId.ToString(),
ResourceKind.Sampler, ShaderStages.Fragment)));
while (true)
{
Console.WriteLine($"{System.Threading.Thread.CurrentThread.ManagedThreadId} creating rset"); …
=> [Vulkan] fix vkDescriptorPool thread unsafety issue

src/Veldrid.ImageSharp/Veldrid.ImageSharp.csproj
This fixes a bug where Veldrid.ImageSharp would not load the entirety of a texture (only the first few rows of pixels).
=> Update ImageSharp to 1.0.4

src/Veldrid.Tests/RenderTests.cs, src/Veldrid/D3D11/D3D11CommandList.cs, src/Veldrid/D3D11/D3D11Formats.cs, src/Veldrid/D3D11/D3D11Pipeline.cs
I wanted to use the `BlendStateDescription.BlendFactor` property along with `BlendFactor.BlendFactor` and `BlendFactor.InverseBlendFactor` enum values in an attachment. It turned out that this function is not implemented properly for the D3D backend. The value of the blend factor is not passed to `OMSetBlendState`, and also `BlendFactor.InverseBlendFactor` is converted to a wrong D3D value.
This pull request fixes the described issue and includes a test.
=> Supporting the BlendFactor in the D3D backend

.github/workflows/dotnet.yml, Directory.Build.props, src/NeoDemo/NeoDemo.csproj, src/Veldrid.MetalBindings/Veldrid.MetalBindings.csproj, src/Veldrid.Tests/ComputeTests.cs, src/Veldrid/D3D11/D3D11Buffer.cs, src/Veldrid/D3D11/D3D11Formats.cs, src/Veldrid/D3D11/D3D11GraphicsDevice.cs, src/Veldrid/D3D11/D3D11Sampler.cs, src/Veldrid/D3D11/D3D11Shader.cs, src/Veldrid/D3D11/D3D11Swapchain.cs, src/Veldrid/D3D11/D3D11Texture.cs, src/Veldrid/Veldrid.csproj
- Update Vortice.Windows to latest 2.1.0 stable release.
- Install .NET SDK 6.0 in CI build for future .NET 6.0 update.
- Cleanup dependencies.
=> Update and improvements.

src/Veldrid.MetalBindings/CALayer.cs, src/Veldrid.MetalBindings/CAMetalLayer.cs, src/Veldrid.MetalBindings/NSObject.cs, src/Veldrid.MetalBindings/NSView.cs, src/Veldrid/MTL/MTLSwapchain.cs, src/Veldrid/Vk/VkSurfaceUtil.cs
Using Veldrid with an external SDL window implementation (not Veldrid's `Sdl2`), SDL provides a ready `NSView`/`UIView` instance with `layer.contentScale` set appropriately for HiDPI support, but Veldrid always creates its own `CAMetalLayer`, potentially ignoring a view's existing metal layer.
Therefore I've changed `VkSurfaceUtil` and `MTLSwapchain` to attempt casting the given view's `CALayer` to `CAMetalLayer` via [`isKindOfClass:`](https://developer.apple.com/documentation/objectivec/1418956-nsobject/1418511-iskindofclass) and use it, otherwise create a new metal layer. (I was hoping something like [`viewWithTag(_:)`](https://developer.apple.com/documentation/appkit/nsview/1483294-viewwithtag) but for classes exists, but alas)
I've also added support for `NSViewSwapchainSource` in …
=> Allow using external `CAMetalLayer`s in Metal and Vulkan

src/Veldrid.MetalBindings/NSView.cs
- Split from #404 
- Mostly (resolves) #402 
In efforts to keep things going (since it's been a while for that PR and most of the changes have already been merged recently, e.g. .NET 6 bump), I've split this specific change out just to get Metal working on Apple Silicon.
Have tested that this works properly for the project I'm using Veldrid on.
=> Fix native crash when running Metal on Apple Silicon

src/NeoDemo/NeoDemo.cs, src/NeoDemo/Objects/FullScreenQuad.cs, src/NeoDemo/Objects/ScreenDuplicator.cs, src/NeoDemo/Scene.cs, src/NeoDemo/SceneContext.cs, src/Veldrid.MetalBindings/MTLColorWriteMask.cs, src/Veldrid.MetalBindings/MTLRenderPipelineColorAttachmentDescriptor.cs, src/Veldrid.OpenGLBindings/OpenGLNative.cs, src/Veldrid.Tests/RenderTests.cs, src/Veldrid/BlendAttachmentDescription.cs, src/Veldrid/BlendHelper.cs, src/Veldrid/ColorWriteMask.cs, src/Veldrid/D3D11/D3D11Formats.cs, src/Veldrid/D3D11/D3D11ResourceCache.cs, src/Veldrid/MTL/MTLFormats.cs, src/Veldrid/MTL/MTLPipeline.cs, src/Veldrid/OpenGL/OpenGLCommandExecutor.cs, src/Veldrid/Vk/VkFormats.cs, src/Veldrid/Vk/VkPipeline.cs
I was relying on `BlendFactor` at first, but turns out that doesn't really play well with OpenGL. So I looked at adding support for color write masks instead, which exists in all graphics APIs and is fairly simple to implement.
=> Add "color write" masking support in blend attachments

src/Veldrid/OpenGL/OpenGLUtil.cs
Fix possible StackOverflowException (in case of a crazy opengl driver)
Fix `""` (empty) label causing crash (because `stackalloc byte[0]` returns `(byte*) null`
Improve performance by using a constant-sized stackalloc
Use null-terminated string
=> Use constant stackalloc in SetObjectLabel

src/Veldrid.ImGui/ImGuiRenderer.cs
This makes it easier to identify resources belonging to the imgui rendering in renderdoc
=> Name all resources created in ImGuiRenderer

Directory.Build.props, src/Veldrid/D3D11/D3D11Buffer.cs, src/Veldrid/D3D11/D3D11GraphicsDevice.cs, src/Veldrid/D3D11/D3D11Shader.cs, src/Veldrid/D3D11/D3D11Texture.cs, src/Veldrid/Veldrid.csproj
Eric, 
This pull request is needed to fix a crash that is currently occurring on Intel Integrated Graphics (M360 specifically).   The crash occurs due to Vortice 2.1.0 incorrectly setting a uniform buffer pointer to IntPtr.Zero in VSUnsetConstantBuffer (ID3D11DeviceContext.cs).   Recent changes have corrected the issue.
=> Update to Vortice 2.1.32 to fix crash on M360 Intel Integrated Graphics

src/Veldrid.OpenGLBindings/Enums.cs, src/Veldrid.OpenGLBindings/OpenGLNative.cs, src/Veldrid/OpenGL/OpenGLPipeline.cs
Fixed a few instances of CA2014 ("Do not use stackalloc in loops"), and also added better exception messages after trying to use an invalid structured buffer name when compiling with GL_VALIDATE_SHADER_RESOURCE_NAMES.
=> Add validation of GL structured buffer names, fix warnings due to stackalloc inside loops.

Directory.Build.props, src/Veldrid.Tests/RenderTests.cs, src/Veldrid.Tests/Veldrid.Tests.csproj, src/Veldrid.VirtualReality.Sample/Veldrid.VirtualReality.Sample.csproj, src/Veldrid.VirtualReality/Veldrid.VirtualReality.csproj, src/Veldrid/Veldrid.csproj
- Update Vortice.Windows to latest 2.3.0 stable version.
- Bump LangVersion to 8.0 as required by Vortice.Windows (PolySharp deps)
=> Update Vortice.Windows to latest stable version.

src/Veldrid/Vk/VkSwapchainFramebuffer.cs
After initializing the array for _scImages, SetNewSwapchain only checks that _scImages == null. However, after _scImages is set to the length of scImageCount, scImageCount can increase in value, causing an index outside of the bounds of the array error. This change initializes _scImages as an empty array, and the check for null is replaced by a check for if _scImages.Length < scImageCount.
=> Fix Vulkan _scImages array not resizing when scImageCount changes

src/Veldrid/Vk/VkDescriptorPoolManager.cs
An incorrect count comparison leads to integer underflow of the `PoolInfo.StorageBufferCount` variable.
This in turn allows the pool to be used for an allocation it can not perform, resulting in a `VK_ERROR_OUT_OF_POOL_MEMORY` exception
=> Fixed incorrect count comparison in VkDescriptorPoolManager

src/Veldrid/D3D11/D3D11CommandList.cs
I have a VBO with two different vertex strides inside it.
`SetVertexBufferCore` normally sets `_vertexBindingsChanged = true`, but this isn't happening because the VBO isn't getting rebound.
=> Flush vertex bindings when vertex strides change

src/Veldrid.MetalBindings/MTLResourceOptions.cs, src/Veldrid.MetalBindings/MTLStorageMode.cs
When running Veldrid + Metal under .NET 8, the app crashes with a trace that looks like the one below.
My investigation into this led to the following conclusion:
- [MTLResourceOptions](https://developer.apple.com/documentation/metal/mtlresourceoptions?language=objc) derives from `NSUInteger`.
- [NSUInteger](https://developer.apple.com/documentation/objectivec/nsuinteger?language=objc) is said to be treated as a 64-bit unsigned integer on 64-bit platforms. 32-bit macOS/iOS doesn't exist anymore, so this is the only one we care about.
- I've looked at Xamarain.iOS' [implementation](https://github.com/xamarin/xamarin-macios/blob/300f6ea92d83556f2e5c31189ae69b7cb8c00cc0/src/Metal/MTLEnums.cs#L693-L718) of this same enum, and they also override ulong.
I believe this is caused by some change …
=> Fix marshalling of MTLResourceOptions on .NET 8

src/Veldrid/Vk/CommonStrings.cs, src/Veldrid/Vk/VkGraphicsDevice.cs
Currently using Vulkan on MacOS using MoltenVK causes a validation error related to the `VK_KHR_portability_enumeration` extension. The MoltenVK documentation states: 
> Because MoltenVK supports the VK_KHR_portability_subset extension, when using the Vulkan Loader from the Vulkan SDK to run MoltenVK on macOS, the Vulkan Loader will only include MoltenVK VkPhysicalDevices in the list returned by vkEnumeratePhysicalDevices() if the VK_INSTANCE_CREATE_ENUMERATE_PORTABILITY_BIT_KHR flag is enabled in vkCreateInstance(). See the description of the VK_KHR_portability_enumeration extension in the Vulkan specification for more information about the use of the VK_INSTANCE_CREATE_ENUMERATE_PORTABILITY_BIT_KHR flag.
This is reproducible in NeoDemo by just switching to the Vulkan backend.
=> Add VK_KHR_portability_enumeration extension and flag

src/Veldrid/Vk/VkCommandList.cs
Fixes issue #529.
The memory barrier inserted after a uniform buffer copy in the Vulkan backend did not ensure proper ordering of uniform buffer reads in the shaders. This pull request adds the appropriate flag when the destination buffer is a uniform buffer.
=> Add UniformRead to Vulkan memory barriers for uniform buffers

src/Veldrid/Vk/VkCommandList.cs
My previous pull request #530 accidentally introduced a Vulkan validation error (sorry about that). This pull request resolves the Vulkan validation error by adjusting the scope of uniform buffer copies to comply with the Vulkan spec. The behaviors of all other buffer copies are unchanged.
Specifically, this changes the destination operation in the memory barrier to cover all shader types instead of reading the vertex input (the Vulkan spec only allows combining `UNIFORM_READ_BIT` with the shader scopes, not with the vertex input scope). It also removes `VertexAttributeRead` as a destination access mask for uniform buffers as that combination is not permitted by the spec. 
Altogether, this treats the copy to a uniform buffer in a separate way from other buffer copies in such a way that …
=> Fix Vulkan validation issue with uniform shader memory barriers
