- LICENSE
- src/Veldrid/Graphics/DeviceBuffer.cs
- src/Veldrid/Graphics/Direct3D/D3DDepthStencilState.cs
- src/Veldrid/Graphics/Direct3D/D3DShaderTextureBindingSlots.cs
- src/Veldrid/Graphics/MeshData.cs
- src/Veldrid/Octree.cs
add attribute Flags for bit operation
> fix ctor D3DDepthStencilState

- src/NeoDemo/Camera.cs
- src/NeoDemo/InputTracker.cs
- src/NeoDemo/NeoDemo.cs
- src/NeoDemo/Scene.cs
- src/Veldrid.SDL2/Sdl2.Mouse.cs
- src/Veldrid.SDL2/Sdl2Window.cs
Add wrapper for SDL_SetRelativeMouseMode and SDL_CaptureMouse.
Also add comments for existing Sdl2.Mouse methods.
> Add wrapper for SDL_SetRelativeMouseMode and SDL_CaptureMouse.

- src/Veldrid.ImageSharp/ImageSharpCubemapTexture.cs
Need this to load existing mip levels from papermill specular cubemap:
https://github.com/ux3d/glTF-Sample-Environments/tree/master/papermill/specular
> Cubemap from existing mip maps.

- src/Veldrid.Utilities/BoundingBox.cs
This one should be pretty self-explanatory; have a look...
Brian
> Bug in Veldrid.Utilities/BoundingBox Contains()

- src/Veldrid.Tests/RenderTests.cs
- src/Veldrid.Tests/Shaders/FullScreenTriSampleTexture2D.frag
- src/Veldrid.Tests/Shaders/FullScreenTriSampleTexture2D.vert
- src/Veldrid.Tests/Veldrid.Tests.csproj
Hi @mellinoe,
I've added in a RenderTest as you suggested which can reproduce the bug on the D3D11 backend. I've also given you access to modify the branch so feel free to change whatever you feel like, no need to check with me first.
I loaded the details into the issue here: #247
> Add texture binding test

- src/NeoDemo/Objects/Skybox.cs
- src/Veldrid.ImageSharp/ImageSharpCubemapTexture.cs
- src/Veldrid.ImageSharp/ImageSharpTexture.cs
- src/Veldrid.ImageSharp/Veldrid.ImageSharp.csproj
- src/Veldrid.VirtualReality.Sample/Program.cs
As the title says this will update ImageSharp to the latest released version and makes some minor adjustments to the changes in this version.
This will fix issue [Issue240](https://github.com/mellinoe/veldrid/issues/240)
> Update ImageSharp to beta0007

- src/Veldrid/D3D11/D3D11CommandList.cs
Pretty much the same issue Vulkan had, trivial fix.
> [D3D11] Replace a foreach that was causing a lot of allocations.

- src/Veldrid/D3D11/D3D11CommandList.cs
> [D3D11] Fix ClearDepthStencil not clearing depth.

- src/Veldrid/FramebufferAttachmentDescription.cs
Fixes the validation code not taking cubemaps into account.
> Fix cubemap framebuffer attachments.

- src/Veldrid.ImageSharp/ImageSharpCubemapTexture.cs
- src/Veldrid.ImageSharp/ImageSharpTexture.cs
- src/Veldrid.ImageSharp/MipmapHelper.cs
- src/Veldrid.ImageSharp/Veldrid.ImageSharp.csproj
Updated code to use latest rc1 of imagesharp
> Update veldrid.imagesharp code to use image sharp rc1

- src/Veldrid.SDL2/Sdl2.Mouse.cs
Adds a set of bindings to allow for setting the cursor.
> Add SDL Cursor bindings

- src/Veldrid/D3D11/D3D11GraphicsDevice.cs
- src/Veldrid/GraphicsDeviceFeatures.cs
- src/Veldrid/MTL/MTLGraphicsDevice.cs
- src/Veldrid/OpenGL/OpenGLExtensions.cs
- src/Veldrid/OpenGL/OpenGLGraphicsDevice.cs
- src/Veldrid/Vk/VkGraphicsDevice.cs
Resolve #296 
Not sure I'm doing it right.
> Add support for float64 in shaders

- src/Veldrid/D3D11/D3D11GraphicsDevice.cs
- src/Veldrid/D3D11/D3D11ResourceFactory.cs
- src/Veldrid/D3D11/D3D11Swapchain.cs
- src/Veldrid/D3D11/D3D11Util.cs
- src/Veldrid/Veldrid.csproj
This fixes #305 but also improvements Vortice.Direct3D11 usage with new methods added for better performance.
> Fix IDXGIAdapter leakage and improvementes

- src/Veldrid/D3D11/D3D11CommandList.cs
- src/Veldrid/D3D11/D3D11GraphicsDevice.cs
- src/Veldrid/Veldrid.csproj
Update to latest Vortice.Windows and map directly use Veldrid.Viewport in D3D11.
> Update to latest Vortice.Windows 

- src/Veldrid.RenderDoc/RenderDoc.cs
- src/Veldrid.RenderDoc/RenderDocNative.cs
Added RenderDoc 1.4 API, but the application still uses version 1.2.
> Adding RenderDoc 1.4

- src/Veldrid/D3D11/D3D11Buffer.cs
- src/Veldrid/Veldrid.csproj
- Updated some other dependencies to avoid downgrade warning
- Fixes the critical bug (https://github.com/amerkoleci/Vortice.Windows/issues/119)
> Update to latest 1.9.41 release with critical bug fixed.

- src/Veldrid/D3D11/D3D11GraphicsDevice.cs
- src/Veldrid/Veldrid.csproj
- There was bug with SharpGen during some AddRef and Release marshal of IUnknow.
- Update to latest Vortice.Windows and handle ReportLiveObjects in better way.
> Update to latest Vortice.Windows

- src/Veldrid/Vk/VkBuffer.cs
- src/Veldrid/Vk/VkDeviceMemoryManager.cs
- src/Veldrid/Vk/VkTexture.cs
- src/Veldrid/Vk/VulkanUtil.cs
This improves performance of GPU -> CPU transfers.
Related discussion can be found in #379
> [Vulkan] Use "host cached" memory for staging textures and buffers

- src/Veldrid/Vk/VkGraphicsDevice.cs
> Replaced ConcurrentStack with Stack+lock

- src/Veldrid/CommandList.cs
- src/Veldrid/GraphicsDevice.cs
Just a quality of life improvement.
> Added Span<T> overloads

- .github/workflows/dotnet.yml
- src/Veldrid.Tests/Veldrid.Tests.csproj
> Update .NET SDK version used in GH Action

- src/NeoDemo/NeoDemo.csproj
- src/Veldrid.VirtualReality.Sample/Veldrid.VirtualReality.Sample.csproj
NeoDemo/Sample projects are not packed and pushed to NuGet/MyGet anymore
==Testing Done==
I have validated this MR by executing "ls -l " command to make sure NeoDemo/Sample projects NuGet files aren't created.
> Fixed the issue where GitHub pipeline packed unwanted projects

- .github/workflows/dotnet.yml
Not sure why are you using a very specific version.
> [Minor Change] Update dotnet version

- .github/workflows/dotnet.yml
- Directory.Build.props
- src/NeoDemo/NeoDemo.csproj
- src/Veldrid.ImageSharp/Veldrid.ImageSharp.csproj
- src/Veldrid.Tests/Veldrid.Tests.csproj
- src/Veldrid/D3D11/D3D11Shader.cs
- src/Veldrid/Veldrid.csproj
- ENH: Update to .NET 6.0 and drop .NET5.0
- FIX: D3DCompiler.Compile use flags.
> Target .NET6

- src/Veldrid.ImGui/ImGuiRenderer.cs
https://github.com/ocornut/imgui/issues/4845
> fix IdxOffset field

- src/NeoDemo/NeoDemo.cs
- src/Veldrid.ImGui/ImGuiRenderer.cs
- src/Veldrid.ImGui/Veldrid.ImGui.csproj
NOTE1: due to the following feature of the new imgui input system, a lot we were doing before isn't required anymore.
**This enable input queue trickling to support low framerates.**
NOTE2: Please carefully check the keys, in case I have mapped some of them wrong. I haven't tested each and every key out there.
NOTE3: Added "Show ImGui Demo" in NeoDemo menu for testing purposes, I can remove this if required.
> Updated ImGui to 1.87.3 and use the new input system.

- Directory.Build.props
- src/Veldrid/Veldrid.csproj
Thanks for the merge in NativeLibraryLoader @mellinoe :) - this is the MR for Veldrid to update it to use the new code.
> Update NativeLibraryLoader to v1.0.13
